"""Add user_eligible_jobs association table

Revision ID: 90feccd38453
Revises: d2db9b892344
Create Date: 2026-01-31 19:07:33.960178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90feccd38453'
down_revision: Union[str, None] = 'd2db9b892344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_eligible_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index('idx_user_eligible_jobs_job', 'user_eligible_jobs', ['job_id'], unique=False)
    op.create_index('idx_user_eligible_jobs_user', 'user_eligible_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_eligible_jobs_user', table_name='user_eligible_jobs')
    op.drop_index('idx_user_eligible_jobs_job', table_name='user_eligible_jobs')
    op.drop_table('user_eligible_jobs')
    # ### end Alembic commands ###
