"""Remove website column from companies table and unique constraint

Revision ID: 994c77d01bcc
Revises: 4d9e4ddcbb0c
Create Date: 2026-01-31 21:20:42.296253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994c77d01bcc'
down_revision: Union[str, None] = '4d9e4ddcbb0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_company_name_website'), 'companies', type_='unique')
    op.drop_column('companies', 'website')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_company_name_website'), 'companies', ['name', 'website'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
